name: Pull Request

on: [pull_request_target]

jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: "Greetings from DesignIT Africa! Thanks for making the PR, we will soon review your PR. Thanks :)"